[phases.setup]
nixPkgs = ["nodejs_20", "corepack"]
cmds = ["corepack enable pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[phases.start]
cmd = "pnpm start"

[variables]
NODE_ENV = "production"
